variable "admin-user" {}
variable "password" {}
variable "private_linux_ip" {}
variable "interfaces" {}
variable "key_name" {}
variable "tags" {}
variable "arch" {}  
variable "ver" {}
variable "license" {}
variable "role" {}
variable "fortigate_name" {}
variable "HA3" {}
variable "ha_peer_ip" {}
variable IAM_profile {}