variable "admin-user" {}
variable "password" {}
variable "private_linux_ip" {}
variable "interfaces" {}
variable "key_name" {}
variable "tags" {}
variable "arch" {}  
variable "ver" {}
variable "role" {}
variable "fortigate_name" {}
variable "HA3" {}
variable "ha_peer_ip" {}
variable "IAM_profile" {}
variable "license_file" {}
variable "license_type" {}
variable "vpc_cidr_block" {}
variable "private_gw" {}